import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
WEB_ROOT = ROOT / "src" / "web"


class FrontendSettingsUiTests(unittest.TestCase):
    def test_index_is_now_a_minimal_chat_and_file_viewer_shell(self):
        html = (WEB_ROOT / "index.html").read_text(encoding="utf-8")
        self.assertIn('id="sidebarToggle"', html)
        self.assertIn('class="shell-toggle-icon"', html)
        self.assertIn('aria-label="Open sidebar"', html)
        self.assertIn('data-tooltip="Open sidebar"', html)
        self.assertIn('id="viewerToggle"', html)
        self.assertIn('data-tooltip="Open file browser"', html)
        self.assertIn('class="sidebar-rail"', html)
        self.assertIn('id="newChatButton"', html)
        self.assertIn('id="workspaceSettingsButton"', html)
        self.assertIn('id="refreshWorkspaceButton"', html)
        self.assertIn('id="openInTabButton"', html)
        self.assertIn('id="downloadFileButton"', html)
        self.assertIn('id="refreshContextEvalButton"', html)
        self.assertIn('id="contextEvalReport"', html)
        self.assertIn('id="conversationList"', html)
        self.assertIn('id="chatMessages"', html)
        self.assertIn('id="scrollToBottomButton"', html)
        self.assertIn('id="composerAttachments"', html)
        self.assertIn('id="composerInput"', html)
        self.assertIn('rows="2"', html)
        self.assertIn('id="connectionBadge"', html)
        self.assertIn('id="composerHint"', html)
        self.assertIn('id="fixtureReviewFilter"', html)
        self.assertIn('<option value="suggested">Suggested</option>', html)
        self.assertIn('id="refreshFixtureReviewButton"', html)
        self.assertIn('id="fixtureReviewList"', html)
        self.assertIn('id="fixtureReviewDetail"', html)
        self.assertIn('id="fileList"', html)
        self.assertIn('id="filePreview"', html)
        self.assertIn('id="viewerMeta"', html)
        self.assertIn('id="viewerModeButton"', html)
        self.assertIn('id="viewerCloseButton"', html)
        self.assertIn('class="icon-button"', html)
        self.assertIn('aria-label="Refresh files"', html)
        self.assertIn('aria-label="Open in new tab"', html)
        self.assertIn('aria-label="Download file"', html)
        self.assertIn('aria-label="Back to file list"', html)
        self.assertIn('aria-label="Close file browser"', html)
        self.assertIn('type="module" src="/static/app.js', html)
        self.assertIn('id="settingsOverlay"', html)
        self.assertIn('id="resetAppButton"', html)
        self.assertNotIn('id="chatTitle"', html)
        self.assertNotIn('id="aboutOverlay"', html)
        self.assertNotIn('id="draftShell"', html)
        self.assertNotIn('id="viewerToggleLabel"', html)
        self.assertNotIn('id="workspaceCurrent"', html)
        self.assertNotIn('id="workspaceRoutingMeta"', html)
        self.assertNotIn('Automatic Routing', html)

    def test_typescript_frontend_keeps_chat_and_file_viewer_entrypoints(self):
        ts = (WEB_ROOT / "app.ts").read_text(encoding="utf-8")
        self.assertIn("interface ConversationSummary", ts)
        self.assertIn("interface ThinkingStatus", ts)
        self.assertIn("async function sendCurrentMessage()", ts)
        self.assertIn("async function loadDirectory(path: string)", ts)
        self.assertIn("async function openFile(path: string)", ts)
        self.assertIn('activePreviewNonce: ""', ts)
        self.assertIn("function withCacheBust(url: string, nonce = \"\")", ts)
        self.assertIn("function workspaceFileApiUrl(path: string, nonce = \"\")", ts)
        self.assertIn('cache: "no-store"', ts)
        self.assertIn("state.activePreviewNonce = String(Date.now());", ts)
        self.assertIn("workspaceFileApiUrl(path, state.activePreviewNonce)", ts)
        self.assertIn("function downloadSelectedFile()", ts)
        self.assertIn("function openSelectedFileInTab()", ts)
        self.assertIn("function shouldRenderTextAsMarkdown(", ts)
        self.assertIn("function shouldRenderTextAsCode(", ts)
        self.assertIn("interface SpreadsheetPreviewPayload", ts)
        self.assertIn("function openSpreadsheetFile(", ts)
        self.assertIn("function renderSpreadsheetPreview(", ts)
        self.assertIn("function buildResponsiveHtmlPreview(", ts)
        self.assertIn("interface WorkspaceFilePayload", ts)
        self.assertIn("section_titles?: string[];", ts)
        self.assertIn("opening_preview?: string;", ts)
        self.assertIn("preview_chunks?: Array<{", ts)
        self.assertIn("function documentStructureMeta(", ts)
        self.assertIn("function renderDocumentStructurePanel(", ts)
        self.assertIn("function formatPreviewChunkLabel(", ts)
        self.assertIn('meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"', ts)
        self.assertIn('const srcdoc = escapeHtml(buildResponsiveHtmlPreview(payload.content || ""));', ts)
        self.assertIn('sandbox="allow-scripts"', ts)
        self.assertIn('.replace(/\\n+/g, " ");', ts)
        self.assertIn('const structureMeta = documentStructureMeta(payload);', ts)
        self.assertIn('filePreview.innerHTML = `${renderDocumentStructurePanel(payload)}<iframe class="file-preview-frame"', ts)
        self.assertIn('fileViewUrl(payload.path, state.activePreviewNonce)', ts)
        self.assertIn('filePreview.innerHTML = `${renderDocumentStructurePanel(payload)}<pre class="preview-code">', ts)
        self.assertIn("Document structure", ts)
        self.assertIn('/spreadsheet?path=', ts)
        self.assertIn("if (isSpreadsheetPreviewPath(path)) {", ts)
        self.assertIn("function isMobileViewport()", ts)
        self.assertIn("function buildThinkingSummary(", ts)
        self.assertIn("function setThinkingStatus(", ts)
        self.assertIn("function clearThinkingStatus()", ts)
        self.assertIn("function syncComposerHeight()", ts)
        self.assertIn("function formatElapsedDuration(", ts)
        self.assertIn("function findAssistantWorkStartedAt(", ts)
        self.assertIn("function assistantMetaLabel(", ts)
        self.assertIn("function isSuppressedAssistantNote(", ts)
        self.assertIn("function cleanConversationText(", ts)
        self.assertIn("function displayConversationTitle(", ts)
        self.assertIn("function displayConversationPreview(", ts)
        self.assertIn("function shouldMaterializePastedText(", ts)
        self.assertIn("async function materializeComposerPaste(", ts)
        self.assertIn("interface PendingComposerAttachment", ts)
        self.assertIn("pendingAttachments: [] as PendingComposerAttachment[]", ts)
        self.assertIn("composerUploadingCount: 0", ts)
        self.assertIn("function pendingAttachmentPaths()", ts)
        self.assertIn("function syncComposerActions()", ts)
        self.assertIn("function renderComposerAttachments()", ts)
        self.assertIn("async function uploadComposerFiles(", ts)
        self.assertIn("function removePendingAttachment(", ts)
        self.assertIn("function setComposerUploadState(", ts)
        self.assertIn('const composerAttachments = query<HTMLDivElement>("#composerAttachments")', ts)
        self.assertIn('composerForm.classList.toggle("drag-active", active);', ts)
        self.assertIn('composerAttachments.hidden = false;', ts)
        self.assertIn('class="composer-attachment-chip"', ts)
        self.assertIn('class="composer-attachment-chip uploading"', ts)
        self.assertIn('class="composer-attachment-remove"', ts)
        self.assertIn('data-remove-path="${escapeHtml(attachment.path)}"', ts)
        self.assertIn('Uploading ${state.composerUploadingCount} file', ts)
        self.assertIn('new FormData()', ts)
        self.assertIn('formData.append("target_path", ".");', ts)
        self.assertIn('`/api/workspaces/${encodeURIComponent(state.currentWorkspaceId)}/upload`', ts)
        self.assertIn('const droppedFiles = [...(event.dataTransfer?.files || [])];', ts)
        self.assertIn('sendButton.disabled = state.composerUploadingCount > 0 && !state.generating;', ts)
        self.assertIn('selectedFileContentKind: ""', ts)
        self.assertIn("async function loadContextEvalReport()", ts)
        self.assertIn("function renderContextEvalReport()", ts)
        self.assertIn('type ViewerMode = "closed" | "tree" | "file";', ts)
        self.assertIn('viewerMode: "closed" as ViewerMode', ts)
        self.assertIn("async function promoteContextEvalCapture(", ts)
        self.assertIn("async function inspectFixtureFromTriage(", ts)
        self.assertIn("function workspaceRelativeCapturePath(sourcePath: string)", ts)
        self.assertIn("function suggestContextEvalFixtureName(bucket: ContextEvalTriageBucket, exampleCase: ContextEvalExampleCase)", ts)
        self.assertIn("function describeFixtureCoverage(", ts)
        self.assertIn("function renderFixtureReviewList()", ts)
        self.assertIn("async function loadContextEvalFixtures()", ts)
        self.assertIn("function renderFixtureReviewDetail()", ts)
        self.assertIn("async function loadSelectedFixtureDetails()", ts)
        self.assertIn('"/api/context-evals/auto-draft"', ts)
        self.assertIn('/api/context-evals/fixtures/detail?fixture_path=', ts)
        self.assertIn('"/api/context-evals/fixtures"', ts)
        self.assertIn('"/api/context-evals/fixtures/review"', ts)
        self.assertIn("covered by accepted fixture", ts)
        self.assertIn("suggested fixture queued", ts)
        self.assertIn("needs promotion", ts)
        self.assertIn("suggested candidate fixture", ts)
        self.assertIn("Suggested Promotion", ts)
        self.assertIn("Draft name:", ts)
        self.assertIn("Promote as Candidate", ts)
        self.assertIn("Inspect ${escapeHtml(fixture.review_status)} fixture", ts)
        self.assertIn('"/api/context-evals/promote"', ts)
        self.assertIn('Review status (suggested, candidate, accepted, superseded)', ts)
        self.assertIn('data-fixture-status="suggested"', ts)
        self.assertIn("function connectWebSocket()", ts)
        self.assertIn('event.type === "reasoning_note"', ts)
        self.assertIn('event.type === "status"', ts)
        self.assertIn('turn_kind: "visible_chat"', ts)
        self.assertIn('mode: "auto"', ts)
        self.assertIn("features: {", ts)
        self.assertIn("workspace_write: true", ts)
        self.assertIn("auto_approve_tool_permissions: true", ts)
        self.assertIn("attachments,", ts)
        self.assertIn('type: "permission_response"', ts)
        self.assertIn("function syncShellLayout()", ts)
        self.assertIn("function openFileTree()", ts)
        self.assertIn("function closeViewer()", ts)
        self.assertIn("function isNearBottom(", ts)
        self.assertIn("function syncScrollJumpButton()", ts)
        self.assertIn("function scrollChatToBottom(", ts)
        self.assertIn("const ARTIFACT_HELPER_TEXT_PATTERNS", ts)
        self.assertIn("function extractArtifactReferences(", ts)
        self.assertIn("function displayFileKindLabel(", ts)
        self.assertIn("function displayFilePreviewLabel(", ts)
        self.assertIn("function parseArtifactMessage(", ts)
        self.assertIn("function unwrapSingleFence(", ts)
        self.assertIn("function extractSingleFenceFromMessage(", ts)
        self.assertIn("function stripSingleFenceFromMessage(", ts)
        self.assertIn("function normalizeArtifactBodyForWrite(", ts)
        self.assertIn("function summarizeArtifactDisplayText(", ts)
        self.assertIn("function renderArtifactObject(", ts)
        self.assertIn("function bindArtifactLinks(", ts)
        self.assertIn("async function materializeArtifactFromAssistant(", ts)
        self.assertIn('latestWorkedFilePath: ""', ts)
        self.assertIn("function setLatestWorkedFile(", ts)
        self.assertIn('class="file-item latest-worked', ts)
        self.assertIn('file-item-kind latest', ts)
        self.assertIn("const artifactBody = parsed.materializedBody;", ts)
        self.assertIn('renderArtifactObject(', ts)
        self.assertIn('displayFileKindLabel(item.path, item.content_kind || "", item.type)', ts)
        self.assertIn('viewerMeta.textContent = `${displayFilePreviewLabel(payload.path, contentKind)} preview`;', ts)
        self.assertIn("function maybeHandleAssistantArtifacts(", ts)
        self.assertIn('fetchJson(`/api/workspaces/${encodeURIComponent(state.currentWorkspaceId)}/file`', ts)
        self.assertIn('class="artifact-ref"', ts)
        self.assertIn('class="artifact-inline-ref"', ts)
        self.assertIn("function normalizeCodeLanguage(", ts)
        self.assertIn("function highlightCode(", ts)
        self.assertIn('return "sql";', ts)
        self.assertIn("language === \"sql\"", ts)
        self.assertIn('stickChatToBottom: true', ts)
        self.assertIn('const scrollToBottomButton = query<HTMLButtonElement>("#scrollToBottomButton")', ts)
        self.assertIn('sidebarToggle.setAttribute("aria-label"', ts)
        self.assertIn('viewerToggle.setAttribute("aria-label"', ts)
        self.assertIn('sidebarToggle.dataset.tooltip = sidebarToggleLabel', ts)
        self.assertIn('viewerToggle.dataset.tooltip = viewerToggleTitle', ts)
        self.assertIn("viewerToggle.hidden = state.viewerMode !== \"closed\";", ts)
        self.assertIn('const showOpenInTabButton = state.viewerMode === "file"', ts)
        self.assertIn('&& state.selectedFileContentKind === "html";', ts)
        self.assertIn('openInTabButton.addEventListener("click"', ts)
        self.assertIn('viewerModeButton.setAttribute("aria-label"', ts)
        self.assertIn('viewerModeButton.dataset.tooltip = viewerModeLabel', ts)
        self.assertIn('downloadFileButton.hidden = !(state.viewerMode === "file" && state.selectedFilePath);', ts)
        self.assertIn('downloadFileButton.addEventListener("click"', ts)
        self.assertIn("await loadDirectory(state.currentDirectoryPath);", ts)
        self.assertIn("await openFile(state.selectedFilePath);", ts)
        self.assertIn('const viewerModeLabel = "Back to file list";', ts)
        self.assertIn("function renameConversation(", ts)
        self.assertIn("function deleteConversation(", ts)
        self.assertIn('composerInput.addEventListener("paste"', ts)
        self.assertIn("Attached pasted file:", ts)
        self.assertIn('data-action="rename"', ts)
        self.assertIn('data-action="delete"', ts)
        self.assertIn('data-tooltip="Rename chat"', ts)
        self.assertIn('data-tooltip="Delete chat"', ts)
        self.assertIn("modelName", ts)
        self.assertIn("healthPollTimer: 0 as number", ts)
        self.assertIn("function thinkingStatusLabel(", ts)
        self.assertIn("void fetchHealth();", ts)
        self.assertIn("window.setInterval(() => {", ts)
        self.assertIn('return "Assistant";', ts)
        self.assertIn('return "Working";', ts)
        self.assertIn('status.phase === "permission"', ts)
        self.assertIn('setThinkingStatus("Switching to the fallback path and continuing."', ts)
        self.assertNotIn("function showAbout()", ts)
        self.assertNotIn("function toggleTheme()", ts)
        self.assertNotIn('const workspaceSelect = query', ts)
        self.assertNotIn('const workspaceCurrent = query', ts)
        self.assertNotIn('const workspaceRoutingMeta = query', ts)
        self.assertNotIn("function currentWorkspaceName()", ts)

    def test_css_focuses_on_two_panel_chat_and_viewer_layout(self):
        css = (WEB_ROOT / "style.css").read_text(encoding="utf-8")
        self.assertIn(".main-grid", css)
        self.assertIn(".shell-toggle", css)
        self.assertIn(".shell-toggle-right", css)
        self.assertIn('body[data-viewer-mode="tree"] .shell-toggle-right', css)
        self.assertIn("body[data-left-sidebar-open=\"true\"] .shell-toggle-left", css)
        self.assertIn(".sr-only", css)
        self.assertIn(".sidebar-rail", css)
        self.assertIn(".rail-button", css)
        self.assertIn(".sidebar-content", css)
        self.assertIn(".icon-button", css)
        self.assertIn(".viewer-open-button", css)
        self.assertIn(".viewer-download-button", css)
        self.assertIn(".spreadsheet-preview", css)
        self.assertIn(".spreadsheet-sheet-picker", css)
        self.assertIn(".preview-table-shell", css)
        self.assertIn("button[data-tooltip]", css)
        self.assertIn("button[data-tooltip]::after", css)
        self.assertIn(".shell-toggle[data-tooltip]", css)
        self.assertIn(".viewer-actions button[data-tooltip]::after", css)
        self.assertIn(".chat-messages", css)
        self.assertIn(".scroll-jump", css)
        self.assertIn(".viewer-layout", css)
        self.assertIn(".viewer-panel", css)
        self.assertIn("body[data-viewer-mode=\"tree\"] .viewer-panel", css)
        self.assertIn("body[data-viewer-mode=\"file\"] .file-browser", css)
        self.assertIn("body[data-viewer-mode=\"tree\"] .chat-panel", css)
        self.assertIn("padding-bottom: calc(128px + env(safe-area-inset-bottom));", css)
        self.assertIn("bottom: calc(env(safe-area-inset-bottom) + 14px);", css)
        self.assertIn(".file-preview-frame", css)
        self.assertIn(".document-structure-panel", css)
        self.assertIn(".document-structure-sections", css)
        self.assertIn(".document-structure-opening", css)
        self.assertIn(".document-structure-chunk", css)
        self.assertIn(".conversation-line", css)
        self.assertIn(".conversation-time", css)
        self.assertIn(".conversation-item.active", css)
        self.assertIn(".conversation-action-button", css)
        self.assertIn(".artifact-ref-list", css)
        self.assertIn(".artifact-object", css)
        self.assertIn(".artifact-object-meta", css)
        self.assertIn(".artifact-object-note", css)
        self.assertIn(".file-item.latest-worked", css)
        self.assertIn(".file-item-kind.latest", css)
        self.assertIn(".file-item-subpath", css)
        self.assertIn(".composer.drag-active", css)
        self.assertIn(".composer-attachments", css)
        self.assertIn(".composer-attachment-chip", css)
        self.assertIn(".composer-attachment-chip.uploading", css)
        self.assertIn(".composer-attachment-kind", css)
        self.assertIn(".composer-attachment-name", css)
        self.assertIn(".composer-attachment-remove", css)
        self.assertIn(".artifact-ref", css)
        self.assertIn(".artifact-inline-ref", css)
        self.assertIn(".rich-text .tok-keyword", css)
        self.assertIn(".context-eval-report", css)
        self.assertIn(".context-eval-drill-grid", css)
        self.assertIn(".context-eval-button", css)
        self.assertIn(".context-eval-suggestion", css)
        self.assertIn(".message-thinking", css)
        self.assertIn(".message-thinking-label", css)
        self.assertIn(".fixture-review-list", css)
        self.assertIn(".fixture-review-detail", css)
        self.assertIn(".fixture-detail-kv-list", css)
        self.assertIn(".settings-section", css)
        self.assertIn(".context-eval-severity.high", css)
        self.assertIn(".context-eval-severity.suggested", css)
        self.assertIn(".status-badge.streaming", css)
        self.assertIn(".status-badge.loading", css)
        self.assertIn(".composer {", css)
        self.assertIn(".composer-runtime", css)
        self.assertIn("overflow-y: hidden;", css)
        self.assertIn(".message-code-block", css)
        self.assertIn(".tok-keyword", css)
        self.assertIn(".preview-markdown .message-code-block", css)
        self.assertIn(".preview-markdown h1", css)
        self.assertIn("--chat-lane-width: 820px;", css)
        self.assertIn(".chat-messages {", css)
        self.assertIn("align-items: stretch;", css)
        self.assertIn("width: 100%;", css)
        self.assertIn("align-self: flex-end;", css)
        self.assertIn("width: fit-content;", css)
        self.assertIn("max-width: 100%;", css)
        self.assertIn("margin: 0 auto;", css)
        self.assertIn("position: sticky;", css)
        self.assertIn("overscroll-behavior: contain;", css)
        self.assertIn("scrollbar-gutter: stable;", css)
        self.assertIn("scrollbar-width: none;", css)
        self.assertIn("-ms-overflow-style: none;", css)
        self.assertIn(".chat-messages::-webkit-scrollbar", css)
        self.assertIn('body[data-left-sidebar-open="true"] .sidebar', css)
        self.assertIn('body[data-viewer-mode="file"] .viewer-panel', css)
        self.assertIn("transform: translateX(-100%);", css)
        self.assertIn("transform: translateX(100%);", css)
        self.assertIn("padding: 60px 12px 12px;", css)
        self.assertIn(".settings-scroll-section", css)
        self.assertIn(".settings-overlay[hidden]", css)


if __name__ == "__main__":
    unittest.main()
