import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
WEB_ROOT = ROOT / "src" / "web"


class FrontendSettingsUiTests(unittest.TestCase):
    def test_index_is_now_a_minimal_chat_and_file_viewer_shell(self):
        html = (WEB_ROOT / "index.html").read_text(encoding="utf-8")
        self.assertIn('id="sidebarToggle"', html)
        self.assertIn('class="shell-toggle-icon"', html)
        self.assertIn('aria-label="Open workspace"', html)
        self.assertIn('id="viewerToggle"', html)
        self.assertIn('id="viewerToggleLabel"', html)
        self.assertIn('id="workspaceCurrent"', html)
        self.assertIn('id="workspaceRoutingMeta"', html)
        self.assertIn('Automatic Routing', html)
        self.assertIn('id="workspaceSettingsButton"', html)
        self.assertIn('id="refreshContextEvalButton"', html)
        self.assertIn('id="contextEvalReport"', html)
        self.assertIn('id="conversationList"', html)
        self.assertIn('id="chatMessages"', html)
        self.assertIn('id="composerInput"', html)
        self.assertIn('rows="2"', html)
        self.assertIn('id="connectionBadge"', html)
        self.assertIn('id="composerHint"', html)
        self.assertIn('id="fixtureReviewFilter"', html)
        self.assertIn('<option value="suggested">Suggested</option>', html)
        self.assertIn('id="refreshFixtureReviewButton"', html)
        self.assertIn('id="fixtureReviewList"', html)
        self.assertIn('id="fixtureReviewDetail"', html)
        self.assertIn('id="fileList"', html)
        self.assertIn('id="filePreview"', html)
        self.assertIn('id="viewerMeta"', html)
        self.assertIn('id="viewerModeButton"', html)
        self.assertIn('id="viewerCloseButton"', html)
        self.assertIn('type="module" src="/static/app.js', html)
        self.assertIn('id="settingsOverlay"', html)
        self.assertIn('id="resetAppButton"', html)
        self.assertNotIn('id="chatTitle"', html)
        self.assertNotIn('id="aboutOverlay"', html)
        self.assertNotIn('id="draftShell"', html)

    def test_typescript_frontend_keeps_chat_and_file_viewer_entrypoints(self):
        ts = (WEB_ROOT / "app.ts").read_text(encoding="utf-8")
        self.assertIn("interface ConversationSummary", ts)
        self.assertIn("async function sendCurrentMessage()", ts)
        self.assertIn("async function loadDirectory(path: string)", ts)
        self.assertIn("async function openFile(path: string)", ts)
        self.assertIn("async function loadContextEvalReport()", ts)
        self.assertIn("function renderContextEvalReport()", ts)
        self.assertIn('type ViewerMode = "closed" | "tree" | "file";', ts)
        self.assertIn('viewerMode: "closed" as ViewerMode', ts)
        self.assertIn("async function promoteContextEvalCapture(", ts)
        self.assertIn("async function inspectFixtureFromTriage(", ts)
        self.assertIn("function workspaceRelativeCapturePath(sourcePath: string)", ts)
        self.assertIn("function suggestContextEvalFixtureName(bucket: ContextEvalTriageBucket, exampleCase: ContextEvalExampleCase)", ts)
        self.assertIn("function describeFixtureCoverage(", ts)
        self.assertIn("function renderFixtureReviewList()", ts)
        self.assertIn("async function loadContextEvalFixtures()", ts)
        self.assertIn("function renderFixtureReviewDetail()", ts)
        self.assertIn("async function loadSelectedFixtureDetails()", ts)
        self.assertIn('"/api/context-evals/auto-draft"', ts)
        self.assertIn('/api/context-evals/fixtures/detail?fixture_path=', ts)
        self.assertIn('"/api/context-evals/fixtures"', ts)
        self.assertIn('"/api/context-evals/fixtures/review"', ts)
        self.assertIn("covered by accepted fixture", ts)
        self.assertIn("suggested fixture queued", ts)
        self.assertIn("needs promotion", ts)
        self.assertIn("suggested candidate fixture", ts)
        self.assertIn("Suggested Promotion", ts)
        self.assertIn("Draft name:", ts)
        self.assertIn("Promote as Candidate", ts)
        self.assertIn("Inspect ${escapeHtml(fixture.review_status)} fixture", ts)
        self.assertIn('"/api/context-evals/promote"', ts)
        self.assertIn('Review status (suggested, candidate, accepted, superseded)', ts)
        self.assertIn('data-fixture-status="suggested"', ts)
        self.assertIn("function connectWebSocket()", ts)
        self.assertIn('turn_kind: "visible_chat"', ts)
        self.assertIn("auto_approve_tool_permissions: true", ts)
        self.assertIn('type: "permission_response"', ts)
        self.assertIn("function syncShellLayout()", ts)
        self.assertIn("function openFileTree()", ts)
        self.assertIn("function closeViewer()", ts)
        self.assertIn("function normalizeCodeLanguage(", ts)
        self.assertIn("function highlightCode(", ts)
        self.assertIn("workspaceCurrent.textContent =", ts)
        self.assertIn("workspaceRoutingMeta.textContent =", ts)
        self.assertIn('sidebarToggle.setAttribute("aria-label"', ts)
        self.assertIn('viewerToggle.setAttribute("aria-label"', ts)
        self.assertIn("function renameConversation(", ts)
        self.assertIn("function deleteConversation(", ts)
        self.assertIn('data-action="rename"', ts)
        self.assertIn('data-action="delete"', ts)
        self.assertIn("modelName", ts)
        self.assertNotIn("function showAbout()", ts)
        self.assertNotIn("function toggleTheme()", ts)
        self.assertNotIn('const workspaceSelect = query', ts)

    def test_css_focuses_on_two_panel_chat_and_viewer_layout(self):
        css = (WEB_ROOT / "style.css").read_text(encoding="utf-8")
        self.assertIn(".main-grid", css)
        self.assertIn(".shell-toggle", css)
        self.assertIn(".shell-toggle-right", css)
        self.assertIn(".shell-toggle-labeled", css)
        self.assertIn("body[data-left-sidebar-open=\"true\"] .shell-toggle-left", css)
        self.assertIn(".sr-only", css)
        self.assertIn(".workspace-current", css)
        self.assertIn(".workspace-routing-meta", css)
        self.assertIn(".chat-messages", css)
        self.assertIn(".viewer-layout", css)
        self.assertIn(".viewer-panel", css)
        self.assertIn("body[data-viewer-mode=\"tree\"] .viewer-panel", css)
        self.assertIn("body[data-viewer-mode=\"file\"] .file-browser", css)
        self.assertIn("body[data-viewer-mode=\"tree\"] .chat-panel", css)
        self.assertIn(".file-preview-frame", css)
        self.assertIn(".conversation-item.active", css)
        self.assertIn(".context-eval-report", css)
        self.assertIn(".context-eval-drill-grid", css)
        self.assertIn(".context-eval-button", css)
        self.assertIn(".context-eval-suggestion", css)
        self.assertIn(".fixture-review-list", css)
        self.assertIn(".fixture-review-detail", css)
        self.assertIn(".fixture-detail-kv-list", css)
        self.assertIn(".settings-section", css)
        self.assertIn(".context-eval-severity.high", css)
        self.assertIn(".context-eval-severity.suggested", css)
        self.assertIn(".status-badge.streaming", css)
        self.assertIn(".status-badge.loading", css)
        self.assertIn(".composer {", css)
        self.assertIn(".composer-runtime", css)
        self.assertIn(".message-code-block", css)
        self.assertIn(".tok-keyword", css)
        self.assertIn("--chat-lane-width: 860px;", css)
        self.assertIn("width: min(var(--chat-lane-width), calc(100% - 28px));", css)
        self.assertIn("margin: 0 auto;", css)
        self.assertIn("position: sticky;", css)
        self.assertIn(".settings-scroll-section", css)
        self.assertIn(".settings-overlay[hidden]", css)


if __name__ == "__main__":
    unittest.main()
