import type {
    ChatMessage,
    ConnectionState,
    ContextEvalFixtureDetailRecord,
    ContextEvalFixtureRecord,
    ContextEvalReport,
    ConversationSummary,
    PendingComposerAttachment,
    ThinkingStatus,
    ViewerMode,
    WorkspaceItem,
    WorkspaceSummary,
} from "./types.js";

export const state = {
    appTitle: document.body.dataset.appTitle || "AI Chat",
    ws: null as WebSocket | null,
    reconnectTimer: 0 as number,
    connectionState: "offline" as ConnectionState,
    generating: false,
    modelAvailable: false,
    modelName: "",
    workspaces: [] as WorkspaceSummary[],
    currentWorkspaceId: localStorage.getItem("lastWorkspaceId") || "",
    conversations: [] as ConversationSummary[],
    currentConversationId: "",
    currentConversationTitle: "New chat",
    messages: [] as ChatMessage[],
    activeAssistantIndex: -1,
    currentDirectoryPath: ".",
    fileItems: [] as WorkspaceItem[],
    selectedFilePath: "",
    selectedFileContentKind: "",
    latestWorkedFilePath: "",
    leftSidebarOpen: false,
    viewerMode: "closed" as ViewerMode,
    contextEvalReport: null as ContextEvalReport | null,
    contextEvalLoading: false,
    contextEvalError: "",
    selectedContextEvalBucketKey: "",
    selectedContextEvalExampleIndex: 0,
    contextEvalFixtures: [] as ContextEvalFixtureRecord[],
    fixtureReviewLoading: false,
    fixtureReviewFilter: "all",
    selectedFixturePath: "",
    compareFixturePath: "",
    selectedFixtureDetail: null as ContextEvalFixtureDetailRecord | null,
    compareFixtureDetail: null as ContextEvalFixtureDetailRecord | null,
    fixtureDetailLoading: false,
    thinkingStatus: null as ThinkingStatus | null,
    stickChatToBottom: true,
    handledArtifactKeys: new Set<string>(),
    conversationRefreshTimer: 0 as number,
    healthPollTimer: 0 as number,
    pendingAttachments: [] as PendingComposerAttachment[],
    composerUploadingCount: 0,
    composerDropActive: false,
    activeStreamConversationId: "",
    activePreviewNonce: "",
};

export const PASTE_ATTACH_CHAR_THRESHOLD = 1200;
export const PASTE_ATTACH_LINE_THRESHOLD = 28;
export const FIRST_TURN_COMPOSER_MAX_HEIGHT = 260;
export const LATER_TURN_COMPOSER_MAX_HEIGHT = 152;
